"""model updated

Revision ID: 2e177cbd5c7b
Revises: 39a20addf3b6
Create Date: 2024-08-23 09:16:44.673114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e177cbd5c7b'
down_revision = '39a20addf3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parva_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sandhi_number', sa.Integer(), nullable=False))
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('sandhi_number')

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.drop_column('parva_number')

    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
