"""model updated

Revision ID: 39a20addf3b6
Revises: 
Create Date: 2024-08-19 09:23:39.946757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39a20addf3b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
