"""model updated

Revision ID: 5624cde158ff
Revises: 2e177cbd5c7b
Create Date: 2024-08-24 14:56:22.198564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5624cde158ff'
down_revision = '2e177cbd5c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['parva_number'])

    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
