"""Add example_column to User model

Revision ID: 6fc87fe724d3
Revises: 
Create Date: 2024-07-27 12:31:43.750300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fc87fe724d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint('uix_sandhi_padya_number', ['sandhi_id', 'padya_number'])

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_unique_constraint('uix_1', ['parva_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.drop_constraint('uix_1', type_='unique')
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('parva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.drop_constraint('uix_sandhi_padya_number', type_='unique')
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.drop_table('users')
    # ### end Alembic commands ###
