"""model updated

Revision ID: a3d6e03c3f69
Revises: 
Create Date: 2024-09-07 17:09:38.215850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3d6e03c3f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akaradi_suchi', schema=None) as batch_op:
        batch_op.drop_column('sandhi_number')
        batch_op.drop_column('parva_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akaradi_suchi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parva_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sandhi_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
