"""model updated

Revision ID: df29e7fd23a5
Revises: 5624cde158ff
Create Date: 2024-09-07 15:49:01.014359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df29e7fd23a5'
down_revision = '5624cde158ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akaradi_suchi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('padyafirstline', sa.Text(), nullable=False),
    sa.Column('parva_id', sa.Integer(), nullable=False),
    sa.Column('sandhi_id', sa.Integer(), nullable=False),
    sa.Column('padya_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parva_id'], ['parva.id'], ),
    sa.ForeignKeyConstraint(['sandhi_id'], ['sandhi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parva_id', 'sandhi_id', 'padya_number', name='unique_parva_sandhi_padya')
    )
    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandhi', schema=None) as batch_op:
        batch_op.alter_column('parva_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('padya', schema=None) as batch_op:
        batch_op.alter_column('sandhi_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.drop_table('akaradi_suchi')
    # ### end Alembic commands ###
